CREATE TABLE IF NOT EXISTS Users (
  id SERIAL PRIMARY KEY ,
  email TEXT UNIQUE NOT NULL,
  login TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Scores (
  id SERIAL PRIMARY KEY,
  user_id  INTEGER REFERENCES Users(id) ON DELETE CASCADE ,
  count_games INTEGER DEFAULT 0,
  count_wins INTEGER DEFAULT 0,
  score INTEGER DEFAULT 0

)