CREATE TABLE IF NOT EXISTS Users (
  id SERIAL PRIMARY KEY ,
  email VARCHAR(50) UNIQUE,
  login VARCHAR(50) UNIQUE,
  password VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Scores (
  id SERIAL PRIMARY KEY,
  user_id  INTEGER REFERENCES Users(id) ON DELETE CASCADE ,
  count_games INTEGER DEFAULT 0,
  count_wins INTEGER DEFAULT 0,
  score INTEGER DEFAULT 0
);